import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@styles/globals.scss';
import Header from '@components/Header';

const tacticSans = localFont({
  src: [
    {
      path: './fonts/TacticSans-Reg.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/TacticSans-Med.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/TacticSans-Bld.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/TacticSans-Blk.woff',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-tactic-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head></head>
      <body className={`${tacticSans.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
